require conf/distro/poky.conf

cardatadir = "${ROOT_HOME}/car"

DISTRO = "rpicar"
DISTRO_NAME = "rpicar"
DISTRO_VERSION = "1.0"

hostname:pn-base-files = "rpicar"

DISTRO_FEATURES = " \
    acl \
    ext2 vfat \
    gobject-introspection-data \
    ipv4 ipv6 \
    ldconfig \
    seccomp \
    systemd \
    usrmerge \
    wifi \
    xattr \
"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "pulseaudio"

INIT_MANAGER = "systemd"
NETWORK_MANAGER = "networkmanager"
PACKAGECONFIG:pn-networkmanager = "systemd wifi nss nmcli readline"

RPI_USE_U_BOOT = "1"
ENABLE_UART = "1"
VIDEO_CAMERA = "1"
GPU_MEM = "128"
PREFERRED_PROVIDER_u-boot-fw-utils = "libubootenv"

IMAGE_INSTALL:append = " \
    networkmanager \
    wireless-regdb-static \
    linux-firmware-rpidistro-bcm43430 \
    kernel-modules \
 \
    ssh-auth \
    balena-wifi-connect \
    test-config \
    tmux \
    htop \
    vim \
\
    gpiosrv \
    rpicar-caddy \
    rpicar-mediamtx \
\
    mediamtx \
    v4l-utils \
    gstreamer1.0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-rtsp-server \
"
PACKAGECONFIG:pn-x264 = ""
PACKAGECONFIG:pn-gstreamer1.0-plugins-base = ""
PACKAGECONFIG:pn-gstreamer1.0-plugins-good = "libv4l2 v4l2 soup3"
PACKAGECONFIG:pn-gstreamer1.0-plugins-bad = "openh264"
PACKAGECONFIG:pn-gstreamer1.0-plugins-ugly = "x264"
SKIP_RECIPE[ffmpeg] = "not necessary"

SYSTEMD_AUTO_ENABLE:pn-dnsmasq = "disable"

EXTRA_IMAGE_FEATURES:append = " ssh-server-openssh"

INHERIT += "distrooverrides"
DISTRO_FEATURES_OVERRIDES += "rpicar-ota"

IMAGE_FSTYPES = "ext4 ext4.gz wic.gz wic.bmap"
